version: '2'

  # Configures database volumes
volumes:
  db-dhis2-data:

services:
  # Creation of dhis2 database
  dhis2_db:
    container_name: dhis2_postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9%4qP7b2H!%J
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - db-dhis2-data:/var/lib/postgresql/data    
  
  # Creation of PgAdmin4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    #networks:
    #  - dhis2-network
    environment:
      PGADMIN_DEFAULT_EMAIL: kmatiya@pih.org
      PGADMIN_DEFAULT_PASSWORD: pihneno2007
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"

  dhis2_service:
    container_name: dhis_service_container
    restart: always
    build: .
    depends_on:
      - dhis2_db
